# -*- coding: utf-8 -*-
# Injecte les titres FR + arcs dans src/data/bleach-videos.json (one-shot).
# Source des titres EN : epguides/Wikipedia, traduction FR fidèle.
import json, io

ARCS = [
    (1, 20, "Agent du Shinigami"),
    (21, 41, "Soul Society : l'entrée"),
    (42, 63, "Soul Society : le sauvetage"),
    (64, 91, "Les Bounts (filler)"),
    (92, 109, "Assaut des Bounts sur la Soul Society (filler)"),
    (110, 131, "Arrancar : l'arrivée"),
    (132, 151, "Arrancar : infiltration du Hueco Mundo"),
    (152, 167, "Arrancar : le combat acharné"),
    (168, 189, "Le nouveau capitaine Shusuke Amagai (filler)"),
    (190, 205, "Arrancar vs Shinigami"),
    (206, 212, "Le passé"),
    (213, 229, "Hueco Mundo"),
    (230, 265, "Zanpakuto : contes inconnus (filler)"),
    (266, 316, "Bataille décisive de Karakura"),
    (317, 342, "L'armée envahissante du Gotei 13 (filler)"),
    (343, 366, "Le Shinigami remplaçant perdu"),
]

T = {
1: "Le jour où je suis devenu Shinigami",
2: "Le travail d'un Shinigami",
3: "Le vœu du grand frère, le vœu de la petite sœur",
4: "La perruche maudite",
5: "Frappe l'ennemi invisible !",
6: "Combat à mort ! Ichigo contre Ichigo",
7: "Salutations d'une peluche",
8: "Le 17 juin, souvenir de pluie",
9: "L'ennemi imbattable",
10: "Assaut sur le terrain sacré !",
11: "Le Quincy légendaire",
12: "Un bras droit plein de douceur",
13: "La fleur et le Hollow",
14: "Dos à dos, un combat à mort !",
15: "Le grand plan de Kon",
16: "La rencontre, Renji Abarai !",
17: "Ichigo meurt !",
18: "Récupère le pouvoir du Shinigami !",
19: "Ichigo devient un Hollow !",
20: "L'ombre de Gin Ichimaru",
21: "Bienvenue dans le monde des Shinigamis !",
22: "L'homme qui hait les Shinigamis",
23: "14 jours avant l'exécution de Rukia",
24: "Rassemblement ! Les 13 divisions",
25: "Percer le centre avec une bombe géante ?",
26: "Formation ! Le pire des duos",
27: "Libère le coup fatal !",
28: "Orihime est prise pour cible",
29: "Percée ! Le filet des Shinigamis se resserre",
30: "La confrontation de Renji",
31: "La résolution de tuer",
32: "Les étoiles et l'égaré",
33: "Miracle ! Le mystérieux nouveau héros",
34: "La tragédie de l'aube",
35: "Assassinat d'Aizen ! Les ténèbres approchent",
36: "Kenpachi Zaraki approche !",
37: "La raison du poing",
38: "Désespoir ! Zangetsu brisé",
39: "L'homme immortel",
40: "Le Shinigami que Ganju a rencontré",
41: "Retrouvailles, Ichigo et Rukia",
42: "Yoruichi, maîtresse de la vitesse, danse !",
43: "Le Shinigami méprisable",
44: "Ishida, les limites du pouvoir !",
45: "Dépasser les limites !",
46: "Archives authentiques ! L'école des Shinigamis",
47: "Les vengeurs",
48: "Hitsugaya rugit !",
49: "Le cauchemar de Rukia",
50: "Le lion qui s'éveille",
51: "Le matin de la sentence",
52: "Renji, serment de l'âme ! Duel à mort avec Byakuya",
53: "La tentation de Gin Ichimaru, la résolution de la destruction",
54: "Un serment accompli ! Ramenez Rukia !",
55: "Le plus fort des Shinigamis ! L'ultime confrontation entre maître et élève",
56: "Bataille supersonique ! Qui sera la déesse de la chevalerie ?",
57: "Mille fleurs de cerisier écrasées ! Zangetsu fend le ciel",
58: "Libération ! La lame noire, le pouvoir miraculeux",
59: "Conclusion du duel à mort ! Fierté blanche et désir noir",
60: "La vérité du désespoir, la dague brandie",
61: "Aizen se dévoile ! Sa terrifiante ambition",
62: "Réunion ! La plus puissante organisation de Shinigamis",
63: "La résolution de Rukia, les sentiments d'Ichigo",
64: "Nouvelle rentrée, Renji débarque dans le monde réel ?!",
65: "La terreur rampante, la deuxième victime",
66: "Percée ! Le piège caché dans le labyrinthe",
67: "Jeu mortel ! Le camarade de classe disparu",
68: "La véritable identité du démon, le secret révélé",
69: "Les Bounts ! Les chasseurs d'âmes",
70: "Le retour de Rukia ! La renaissance de l'équipe des remplaçants",
71: "Le moment de la collision ! Une main maléfique s'approche du Quincy",
72: "Attaque aquatique ! Évasion de l'hôpital verrouillé",
73: "Rassemblement au lieu du destin ! L'homme qui passe à l'action",
74: "Souvenirs d'un clan immortel",
75: "Séisme à la 11e division ! Le Shinigami qui se relève",
76: "Choc frontal ! Friido contre Zangetsu",
77: "La rancune qui s'efface ! Le Shinigami que Kenpachi a abattu",
78: "Révélations choc pour les 13 divisions ! La vérité enfouie dans l'histoire",
79: "Yoshino, la décision de mourir",
80: "Assaut d'un ennemi redoutable ! Une minuscule dernière ligne de défense ?!",
81: "Hitsugaya passe à l'action ! La ville attaquée",
82: "Ichigo contre Daruku ! L'apparition des ténèbres fanées",
83: "L'ombre grise, le secret de la poupée",
84: "Dissolution de l'équipe des remplaçants ? La trahison de Rukia",
85: "Bataille de larmes ! Rukia contre Orihime",
86: "Rangiku danse ! Abats l'ennemi invisible",
87: "Byakuya se mobilise ! Les 13 divisions passent à l'action",
88: "Anéantissement des vice-capitaines ?! Piège dans la grotte souterraine",
89: "Revanche ?! Ishida contre Nemu",
90: "Renji Abarai, l'âme du Bankai !",
91: "Shinigami et Quincy, le pouvoir qui renaît",
92: "Retour dans le monde des Shinigamis",
93: "Assaut des Bounts ! Chaos dans les 13 divisions",
94: "La résolution de Hitsugaya ! Le moment du conflit approche",
95: "Byakuya entre en scène ! La danse des cerisiers qui fendent le vent",
96: "Ichigo, Byakuya, Kariya, la bataille des trois extrêmes !",
97: "Hitsugaya part au combat ! Abats l'ennemi dans la forêt",
98: "Choc ! Kenpachi Zaraki contre Maki Ichinose",
99: "Shinigami contre Shinigami ! Le pouvoir incontrôlable",
100: "Soi Fon meurt ? La fin des forces spéciales",
101: "Le Bankai de Mayuri ! Sawatari, le choc du démon",
102: "Le dernier Quincy ! Le pouvoir explosif",
103: "Ishida, attaquer au-delà des limites !",
104: "Lutte à mort de la 10e division ! La libération de Hyorinmaru",
105: "Kariya ! Compte à rebours vers l'explosion",
106: "Vie et vengeance ! Ishida, le choix ultime",
107: "La lame abattue ! Le moment de la ruine",
108: "Le hurlement des Bounts ! L'ultime affrontement",
109: "Ichigo et Rukia, pensées dans le ciel qui tourne",
110: "Réouverture du commerce de remplaçant ! Le terrifiant nouvel élève",
111: "Choc ! Le vrai visage du père",
112: "Le début de la guerre, les Vizards et les Arrancars",
113: "Prélude à l'apocalypse, l'offensive des Arrancars",
114: "Retrouvailles, Ichigo et Rukia",
115: "Mission ! Les Shinigamis sont arrivés",
116: "Le mauvais œil, Aizen encore",
117: "Le combat de Rukia commence ! La lame blanche glacée",
118: "Le Bankai d'Ikkaku ! Le pouvoir qui brise tout",
119: "L'histoire secrète de l'équipe Zaraki ! Les hommes chanceux",
120: "Hitsugaya vole en éclats ! Hyorinmaru brisé",
121: "Choc ! Le protecteur contre le porteur",
122: "Vizard ! Le pouvoir de l'éveillé",
123: "Ichigo, hollowification complète ?!",
124: "Choc ! Le Bankai noir et le Bankai blanc",
125: "Rapport urgent ! Le terrifiant plan d'Aizen",
126: "Uryu contre Ryuken ! Le choc des Quincys père et fils",
127: "La décision d'Urahara, les pensées d'Orihime",
128: "L'Arrancar du cauchemar ! L'équipe Hitsugaya passe à l'action",
129: "La descente de l'émissaire des ténèbres ! La propagation du mal",
130: "L'ennemi invisible ! La décision impitoyable de Hitsugaya",
131: "Les larmes de Rangiku, la triste séparation du frère et de la sœur",
132: "Hitsugaya, Karin et le ballon de foot",
133: "Le récit de kendo enflammé d'Ikkaku",
134: "Le beau pâtissier, Yumichika !",
135: "Kon trompé ! Rangiku aux aguets...",
136: "Guerre civile au Hueco Mundo ! La mort d'Ulquiorra",
137: "La bataille perfide, le piège d'Aizen",
138: "Le Hueco Mundo bouge encore ! Hitsugaya contre Yammy",
139: "Ichigo contre Grimmjow, le combat des 11 secondes",
140: "Le stratagème d'Ulquiorra, l'instant où le soleil se couche",
141: "Adieu... Kurosaki",
142: "Ordre strict ! Le sauvetage interdit d'Orihime Inoue",
143: "La résurrection de Grimmjow",
144: "Ishida et Chad, l'éveil d'un nouveau pouvoir",
145: "Les Espadas se rassemblent ! L'assemblée royale d'Aizen",
146: "Son nom est Nel ! L'apparition de l'étrange Arrancar",
147: "La forêt des Menos ! À la recherche de Rukia disparue",
148: "Ashido, le Shinigami venu du passé",
149: "À travers la forêt qui s'effondre, un million de Menos",
150: "Serment ! Revenir ici en vie",
151: "La tempête déchaînée ! Rencontre avec l'Arrancar dansant",
152: "Ichigo contre-attaque ! Voici mon Bankai",
153: "La recherche diabolique ! Le plan de Szayel Aporro",
154: "Rukia et Kaien, les tristes retrouvailles",
155: "Rukia riposte ! Libère le Kido du désespoir",
156: "Ishida et Pesche, l'attaque unie de l'amitié",
157: "L'atout d'Ishida, le Seele Schneider",
158: "Bras droit du géant, bras gauche du démon",
159: "Yasutora Sado meurt ! Les larmes d'Orihime",
160: "Testament : ton cœur est ici...",
161: "Le cruel Arrancar, la provocation d'Ulquiorra",
162: "Szayel Aporro rit, le filet qui piège Renji est tendu",
163: "Shinigami et Quincy, le combat contre la folie",
164: "La stratégie d'Ishida, 20 secondes d'attaque et de défense",
165: "L'envie de tuer bouillonne ! Grimmjow jubile",
166: "Acharnement contre acharnement ! Ichigo hollowifié",
167: "L'heure du dénouement, la fin de Grimmjow",
168: "Le nouveau capitaine apparaît ! Son nom est Shusuke Amagai",
169: "Nouveau développement, le dangereux élève transféré !",
170: "Lutte désespérée au clair de lune, l'assassin mystérieux et le Zanpakuto",
171: "Kenryu, la profusion de fleurs pourpres en éclosion",
172: "Kibune part en guerre ! Le vent violent qui fait rage",
173: "L'apparition du grand mal ! Les ténèbres de la maison Kasumioji",
174: "Brise la frontière du miroir ! Ichigo captif",
175: "L'assassin vengeur, Ichigo est visé",
176: "Mystère ! L'assassin dévoreur de sabres",
177: "Le retournement de Rukia, la lame déchaînée",
178: "Le cauchemar révélé, Ichigo dans le miroir",
179: "Confrontation ?! Amagai contre le Gotei 13",
180: "La décision de la princesse, la lame du chagrin",
181: "La 2e division sort ! Ichigo encerclé",
182: "La vraie force d'Amagai, le Zanpakuto libéré !",
183: "Les ténèbres en mouvement ! Le vrai visage de Kibune",
184: "Kira et Kibune, attaque et défense de la 3e division",
185: "Glace et flamme ! Combat acharné entre Amagai et Hitsugaya",
186: "Ordre de sortie ! Réprimez la maison Kasumioji",
187: "Ichigo enrage ! Le secret de l'assassin",
188: "Duel ! Amagai contre Ichigo",
189: "La fierté du Shinigami déchu",
190: "Chapitre Hueco Mundo, reprise !",
191: "Le théâtre de Szayel Aporro",
192: "Le secret de Nel, une beauté plantureuse rejoint la bataille ?!",
193: "L'irrésistible spectacle de marionnettes de la terreur",
194: "Le passé de Neliel",
195: "L'union ultime ! Le sérieux de Pesche",
196: "Entrée en guerre ! La plus puissante armée de Shinigamis apparaît",
197: "Le Bankai de Byakuya, la colère silencieuse",
198: "Les deux scientifiques, le piège de Mayuri",
199: "La résurrection de Szayel Aporro",
200: "Le corps le plus dur ?! Abats Nnoitra",
201: "Nnoitra libéré ! Les bras qui se multiplient",
202: "Conclusion du combat acharné ! Qui est le plus fort ?",
203: "La ville de Karakura se rassemble ! Aizen contre les Shinigamis",
204: "La stratégie de persuasion par seppuku d'Ichigo",
205: "Boum ! Un tournoi de kemari rempli de Hollows",
206: "Le chapitre du passé commence ! La vérité d'il y a 110 ans",
207: "Le nouveau capitaine de la 12e division, Kisuke Urahara",
208: "Aizen et le jeune génie",
209: "La 9e division de Muguruma passe à l'action",
210: "Hiyori meurt ? Le début de la tragédie",
211: "Trahison ! Les manœuvres secrètes d'Aizen",
212: "Sauvez Hirako ! Aizen contre Urahara",
213: "Le détective des funérailles d'âmes, Karakuraizer est né",
214: "Le dernier jour de Karakuraizer",
215: "Défendez Karakura ! Tous les Shinigamis se montrent",
216: "L'élite ! Les quatre Shinigamis",
217: "Charlotte, le beau petit démon",
218: "Kira, le combat au cœur du désespoir",
219: "Le Shikai de Hisagi ! Son nom est...",
220: "Ikkaku tombe ! La crise des Shinigamis",
221: "L'affrontement total ! Shinigamis contre Espadas",
222: "Le duo le plus maléfique ?! Soi Fon et Omaeda",
223: "Un corps miraculeux ! Ggio se libère",
224: "Bataille à 3 contre 1 ! La crise de Rangiku",
225: "Tous les vice-capitaines anéantis ! La terrifiante bête démoniaque",
226: "Fin du combat acharné ? Vers une nouvelle bataille !",
227: "Une merveilleuse erreur",
228: "L'été ! La mer ! Le festival des maillots de bain !",
229: "Le cri de l'âme ? Le Shinigami-tapis est né !",
230: "Un nouvel ennemi ! La matérialisation des Zanpakutos",
231: "Byakuya, disparu avec les fleurs de cerisier",
232: "Sode no Shirayuki contre Rukia ! Le cœur troublé",
233: "Zangetsu devient un ennemi",
234: "Renji surpris ?! Les deux Zabimarus",
235: "Choc ! Hisagi contre Kazeshini",
236: "Libération ! Le nouveau Getsuga Tensho",
237: "Soi Fon, encercler le Zanpakuto",
238: "Amitié ? Haine ? Haineko et Tobiume",
239: "L'éveil de Hyorinmaru ! Le combat acharné de Hitsugaya",
240: "La trahison de Byakuya",
241: "Pour la fierté ! Byakuya contre Renji",
242: "Shinigamis et Zanpakutos, sortie générale",
243: "Duel ! Ichigo contre Senbonzakura",
244: "Le tant attendu... Kenpachi apparaît !",
245: "Poursuivez Byakuya ! Les divisions dans la confusion",
246: "Mission spéciale ! Sauvez le capitaine-commandant Yamamoto !",
247: "Les Shinigamis trompés ! La crise de l'effondrement du monde",
248: "Dragon de glace et dragon de flamme ! L'affrontement des plus forts !",
249: "Le Bankai de Senbonzakura ! Attaque et défense du monde réel",
250: "Cet homme, pour les Kuchiki",
251: "Histoire sombre ! Le pire Shinigami est né",
252: "Byakuya, la vérité derrière sa trahison",
253: "La véritable identité de Muramasa révélée",
254: "Byakuya et Renji, la 6e division de retour",
255: "Chapitre final : Zanpakuto, contes inconnus",
256: "La colère de Byakuya ! La famille Kuchiki s'effondre",
257: "Un nouvel ennemi ! La vraie nature des sabres-bêtes",
258: "Serpent errant, singe torturé",
259: "Terreur ! Le monstre qui rôde sous terre",
260: "Conclusion ?! Hisagi contre Kazeshini",
261: "Le détenteur du pouvoir inconnu ! Orihime est visée",
262: "Haineko pleure ! Le tragique sabre-bête",
263: "Emprisonnés ?! Senbonzakura et Zabimaru",
264: "Bataille de femmes ? Nanao contre Katen Kyokotsu",
265: "Évolution ?! Le prodige de l'ultime sabre-bête",
266: "Ichigo contre Ulquiorra",
267: "Cœurs liés ! Le poing gauche prêt à mourir",
268: "Haine et jalousie, le dilemme d'Orihime",
269: "Ichigo et Uryu, liés dos à dos",
270: "Le début du désespoir... Ichigo, la lame hors d'atteinte",
271: "Ichigo meurt ! Orihime, le cri du chagrin !",
272: "Ichigo contre Ulquiorra, conclusion !",
273: "La furie du requin ! Halibel se libère",
274: "Hitsugaya, les funérailles suicidaires des cent fleurs des cieux gelés !",
275: "Le souffle de la mort approche, le roi qui règne sur la mort !",
276: "Tuer d'un seul coup, Soi Fon, Bankai !",
277: "Climax ! Kyoraku contre Starrk !",
278: "Le cauchemar revient... La résurrection de l'Espada",
279: "Hirako et Aizen... les retrouvailles du destin !",
280: "Hisagi et Tosen, le moment des adieux",
281: "Couronne de mensonges, la rancune de Barragan",
282: "Le pouvoir de l'âme ! Los Lobos, attaquez !",
283: "Starrk, le combat solitaire",
284: "La chaîne des sacrifices... le passé de Halibel",
285: "La rancune centenaire... la vengeance de Hiyori",
286: "Le retour d'Ichigo ! Protégez Karakura",
287: "Histoire parallèle ! Ichigo et la lampe magique",
288: "L'ultime atout ! Ichigo, vers la bataille décisive",
289: "Byakuya contre Kenpachi ?! La mêlée commence",
290: "Pour la justice ?! L'homme qui a déserté les Shinigamis",
291: "Lutte désespérée contre Aizen ! Hirako, Shikai !",
292: "Guerre totale ! Aizen contre les Shinigamis",
293: "La lame de la haine ! Hitsugaya enragé !",
294: "Genryusai scellé",
295: "Tout n'était qu'un piège... des liens manipulés !",
296: "La vérité choquante... le mystérieux pouvoir en Ichigo !",
297: "La lame qui s'étend ?! Ichigo contre Gin !",
298: "Film ! Festival ! Le festival du cinéma des Shinigamis !",
299: "Commémoration d'ouverture ! Chapitre de l'Enfer : prologue",
300: "Urahara apparaît ! Arrêtez Aizen !",
301: "Ichigo perd son envie de se battre ?! L'attente de Gin !",
302: "L'ultime Getsuga Tensho ?! L'entraînement d'Ichigo !",
303: "Monde réel et Shinigamis ! Le spécial Nouvel An !",
304: "Encore une histoire parallèle ! Cette fois l'ennemi est un monstre ?",
305: "Le délire rugit ! Hisagi, direction l'auberge thermale !",
306: "Pour protéger ! Ichigo contre Tensa Zangetsu !",
307: "Situation d'urgence ! Aizen, nouvelle évolution !",
308: "Adieu... Rangiku",
309: "Conclusion du combat acharné ! Libération, l'ultime Getsuga Tensho !",
310: "La résolution d'Ichigo",
311: "Le détective des âmes : Karakuraizer redécolle !",
312: "Investiture ! Le tout nouveau capitaine de la 2e division !",
313: "L'homme qui prend le commandement de la 11e division !",
314: "Le secret d'une belle employée de bureau",
315: "L'amie de Yachiru ! Le Shinigami de la justice apparaît !",
316: "Le jour de congé de Toshiro Hitsugaya !",
317: "L'armée envahissante du Gotei 13 ! Incident inhabituel au Seireitei ?!",
318: "Bataille entre camarades ! Renji contre Rukia ?!",
319: "Le filet de capture d'Ichigo !",
320: "Le Gotei 13 se rassemble dans le monde réel !",
321: "Duel face à soi-même, Ikkaku contre Ikkaku !",
322: "Choc ! Rukia contre Rukia !",
323: "Protégez Ichigo ! La détermination de Nozomi",
324: "Reprenez le Seireitei !",
325: "Pour ceux qui croient ! Byakuya contre Hitsugaya !",
326: "Les deux Hinamori, la résolution de Hitsugaya",
327: "La fierté de la famille Kuchiki ! Byakuya contre Byakuya !",
328: "Battez Kageroza ! Shinigamis, guerre totale !",
329: "La recherche interdite... le secret caché de Nozomi !",
330: "Je veux vivre... ! Le Zanpakuto de Nozomi",
331: "Pour combattre ! L'éveil de Nozomi !",
332: "Le Reigai le plus maléfique apparaît dans le monde réel !",
333: "Détruire Nozomi ?! La décision de Genryusai",
334: "Le reiatsu qui s'épuise ! Ichigo, lutte à mort de l'âme !",
335: "Caché dans le Dangai ? Ichigo est seul ?!",
336: "Poursuivez Kageroza ! Infiltration du département de développement technologique !",
337: "Le créateur des âmes modifiées",
338: "Les pensées de Kon, les pensées de Nozomi",
339: "Protégez Ichigo ! Les liens de l'amitié",
340: "Reigai contre originaux, le combat acharné pour la fierté !",
341: "L'armée envahissante, conclusion finale !",
342: "Merci",
343: "Lycéen en 3e année ! Bien habillé, un nouveau chapitre commence !",
344: "Une dispute au lycée ?! Ichigo et Uryu se battent ensemble !",
345: "Uryu attaqué, une menace approche des amis !",
346: "L'utilisateur de Fullbring, Kugo Ginjo",
347: "Un danger rampant dans la famille Kurosaki ?! La confusion d'Ichigo !",
348: "Le pouvoir du badge de remplaçant, la « fierté » d'Ichigo !",
349: "Prochaine cible : la main du démon vise Orihime !",
350: "L'homme qui a tué un Shinigami remplaçant ?! Tsukishima passe à l'action",
351: "Fullbring, le pouvoir détesté !",
352: "Tsukishima attaque ! L'entraînement contrarié",
353: "Ichigo maîtrise le Fullbring !",
354: "Ichigo contre Ginjo ! Vers l'espace du jeu",
355: "Les Shinigamis entrent en guerre ! Le Seireitei aussi a son spécial Nouvel An !",
356: "Ami ou ennemi ?! Le cœur insondable de Ginjo !",
357: "La menace rampante... le pouvoir de Tsukishima !",
358: "Choc ?! Xcution attaque Ginjo",
359: "La triste bataille ! Ichigo contre Sado et Orihime !",
360: "Ichigo contre Uryu ?! Qui est le traître ?!",
361: "Nouvelle apparence ! Voici le Gotei 13 !",
362: "Résurrection ! Le Shinigami remplaçant, Ichigo Kurosaki !",
363: "Combat féroce ! Shinigamis contre XCUTION !",
364: "Lutte désespérée ?! Les souvenirs troublés de Byakuya",
365: "Ichigo contre Ginjo ! Le secret du badge de remplaçant",
366: "Une histoire qui change, un cœur immuable",
}

def arc_for(ep):
    for lo, hi, name in ARCS:
        if lo <= ep <= hi:
            return name
    return "Bleach"

path = r"F:\brams-web-test\src\data\bleach-videos.json"
with io.open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

assert len(T) == 366, f"titres: {len(T)}"
patched = 0
for entry in data:
    ep = entry.get("episode")
    if ep in T:
        entry["title"] = T[ep]
        entry["arc"] = arc_for(ep)
        patched += 1

with io.open(path, "w", encoding="utf-8", newline="\n") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write("\n")

print(f"OK: {patched}/366 episodes patches")
