// ── Character & Devil Fruit data ──────────────────────────────────────────────
// Images: replace external URLs with your Supabase Storage URLs
// e.g. supabase.storage.from('devil-fruits').getPublicUrl('luffy.jpg').data.publicUrl

export const FRUIT_TYPES = {
  paramecia: { label: 'Paramecia', color: '#1E3A8A', badge: '#3B82F6' },
  logia:     { label: 'Logia',     color: '#065F46', badge: '#10B981' },
  zoan:      { label: 'Zoan',      color: '#7C2D12', badge: '#F97316' },
  mythZoan:  { label: 'Zoan Mythique', color: '#4A1D96', badge: '#8B5CF6' },
  ancient:   { label: 'Zoan Ancien',   color: '#713F12', badge: '#D97706' },
}

export const CHARACTERS = [
  {
    id: 'luffy',
    name: 'Monkey D. Luffy',
    title: 'Le Seigneur des Pirates',
    bounty: '3 000 000 000',
    epithet: 'Joy Boy / Gear 5',
    image: 'https://static.wikia.nocookie.net/onepiece/images/e/e9/Monkey_D._Luffy_Anime_Post_Timeskip_Infobox.png',
    fruit: {
      name: 'Hito Hito no Mi, Modèle : Nika',
      aka: 'Gomu Gomu no Mi',
      type: 'mythZoan',
      description: 'Le fruit du démon le plus puissant du monde. Conféré par le Dieu du Soleil Nika, il transforme son porteur en homme de caoutchouc aux pouvoirs libérateurs. La puissance dépend entièrement de l\'imagination de l\'utilisateur.',
      abilities: ['Corps en caoutchouc', 'Gears 1 à 5', 'Forme Nika / Soleil', 'Conqueror\'s Haki amplifié'],
      color: '#F59E0B',
    },
  },
  {
    id: 'kaido',
    name: 'Kaidou',
    title: 'Le Plus Fort des Animaux',
    bounty: '4 611 100 000',
    epithet: 'Roi des Bêtes',
    image: 'https://birdsofherme.wordpress.com/wp-content/uploads/2018/10/kaido.png?w=1400',
    fruit: {
      name: 'Uo Uo no Mi, Modèle : Seiryu',
      type: 'mythZoan',
      description: 'Fruit Zoan mythique qui transforme son porteur en dragon bleu céleste. Kaidou est réputé être la créature vivante la plus forte du monde, invulnérable à toute arme conventionnelle.',
      abilities: ['Transformation dragon', 'Kaido du "Ciel"', 'Souffle de foudre (Flame Clouds)', 'Corps invulnérable'],
      color: '#3B82F6',
    },
  },
  {
    id: 'whitebeard',
    name: 'Edward Newgate',
    title: 'Le Plus Puissant Homme du Monde',
    bounty: '5 046 000 100',
    epithet: 'Barbe-Blanche',
    image: 'https://staticg.sportskeeda.com/editor/2025/07/c256c-17524689497635-1920.jpg',
    fruit: {
      name: 'Gura Gura no Mi',
      type: 'paramecia',
      description: 'Fruit du démon le plus puissant de type Paramecia, capable de générer des tremblements de terre et des tsunamis. Porteur de la force de détruire le monde entier selon les dires.',
      abilities: ['Tremblements de terre', 'Tsunamis', 'Fissures spatiales', 'Vibrations destructrices'],
      color: '#F97316',
    },
  },
  {
    id: 'akainu',
    name: 'Sakazuki',
    title: 'Amiral de la Flotte',
    bounty: null,
    epithet: 'Akainu / Chien Rouge',
    image: 'https://seakoff.com/cdn/shop/articles/akainu-from-one-piece-the-fearsome-magma-admirals-power-and-legacy-959747.webp?v=1718531233',
    fruit: {
      name: 'Magu Magu no Mi',
      type: 'logia',
      description: 'Fruit Logia de type magma. Considéré comme la puissance offensive la plus redoutable parmi les fruits Logia. Le magma est plus chaud que le feu et peut le brûler.',
      abilities: ['Corps de magma', 'Attaques volcaniques', 'Résistance absolue au feu', 'Lave inextinguible'],
      color: '#DC2626',
    },
  },
  {
    id: 'aokiji',
    name: 'Kuzan',
    title: 'Ancien Amiral',
    bounty: null,
    epithet: 'Aokiji / Phasme Bleu',
    image: 'https://i.redd.it/miauf1nv6yde1.jpeg',
    fruit: {
      name: 'Hie Hie no Mi',
      type: 'logia',
      description: 'Fruit Logia de glace. Son porteur peut créer, contrôler et se transformer en glace. Kuzan a gelé une mer entière lors de son combat avec Akainu à Punk Hazard.',
      abilities: ['Corps de glace', 'Gel instantané', 'Pont de glace sur l\'océan', 'Résurrection par le gel'],
      color: '#06B6D4',
    },
  },
  {
    id: 'kizaru',
    name: 'Borsalino',
    title: 'Amiral de la Marine',
    bounty: null,
    epithet: 'Kizaru / Amiral Chien Jaune',
    image: 'https://www.dexerto.fr/cdn-image/wp-content/uploads/sites/2/2024/06/20/kizaru-one-piece.jpg?width=1200&quality=60&format=auto',
    fruit: {
      name: 'Pika Pika no Mi',
      type: 'logia',
      description: 'Fruit Logia de la lumière. Son porteur se déplace à la vitesse de la lumière et génère des lasers destructeurs. La vélocité absolue en combat.',
      abilities: ['Vitesse de la lumière', 'Lasers de photons', 'Corps de lumière immatériel', 'Épée de lumière'],
      color: '#FBBF24',
    },
  },
  {
    id: 'blackbeard',
    name: 'Marshall D. Teach',
    title: 'Yonkou',
    bounty: '3 996 000 000',
    epithet: 'Barbe-Noire',
    image: 'https://www.mangamag.fr/wp-content/uploads/2023/08/barbe-noire-one-piece-illustration-scaled.jpg',
    fruit: {
      name: 'Yami Yami no Mi + Gura Gura no Mi',
      type: 'logia',
      description: 'Premier et unique cas connu d\'un humain portant deux fruits du démon. Le Yami Yami neutralise les pouvoirs adverses par attraction gravitationnelle des ténèbres.',
      abilities: ['Ténèbres gravitationnelles', 'Annulation de pouvoirs', 'Tremblements (Gura Gura)', 'Absorption dans le vide'],
      color: '#1F2937',
    },
  },
  {
    id: 'marco',
    name: 'Marco le Phoenix',
    title: 'Premier Lieutenant de Barbe-Blanche',
    bounty: '1 374 000 000',
    epithet: 'Phoenix',
    image: 'https://i.redd.it/bgv9g0g3zehb1.jpg',
    fruit: {
      name: 'Tori Tori no Mi, Modèle : Phénix',
      type: 'mythZoan',
      description: 'Fruit Zoan mythique phénix aux flammes bleues régénératrices. Contrairement au feu ordinaire, les flammes de Marco soignent les blessures plutôt que de brûler.',
      abilities: ['Transformation Phénix', 'Régénération par flammes bleues', 'Vol', 'Guérison quasi-totale'],
      color: '#3B82F6',
    },
  },
  {
    id: 'law',
    name: 'Trafalgar D. Water Law',
    title: 'Capitaine des Heart Pirates',
    bounty: '3 000 000 000',
    epithet: 'Chirurgien de la Mort',
    image: 'https://pbs.twimg.com/media/GNeCpepX0AALhEk.jpg',
    fruit: {
      name: 'Ope Ope no Mi',
      type: 'paramecia',
      description: 'Fruit convoité comme le fruit le plus précieux du monde. Crée une "salle d\'opération" où le porteur contrôle tout à l\'intérieur. Peut accorder l\'immortalité — au prix de la mort de l\'utilisateur.',
      abilities: ['Room — salle d\'opération', 'Shambles (téléportation)', 'Amputation sans dommage', 'Immortalité (ultimate)'],
      color: '#8B5CF6',
    },
  },
  {
    id: 'ace',
    name: 'Portgas D. Ace',
    title: 'Commandant de Barbe-Blanche',
    bounty: '550 000 000',
    epithet: 'As de Feu / Poing de Feu',
    image: 'https://www.japanfm.fr/wp-content/uploads/2023/01/Ace-scaled.webp',
    fruit: {
      name: 'Mera Mera no Mi',
      type: 'logia',
      description: 'Fruit Logia du feu. Son porteur peut créer, contrôler et se transformer en feu. L\'un des fruits Logia les plus offensifs. Actuellement en possession de Sabo.',
      abilities: ['Corps de feu', 'Feu de Joie (flammes intenses)', 'Résistance au feu', 'Tempête de feu'],
      color: '#EF4444',
    },
  },
  {
    id: 'robin',
    name: 'Nico Robin',
    title: 'Archéologue des Straw Hat',
    bounty: '930 000 000',
    epithet: 'Fleur du Diable',
    image: 'https://gear5world.com/cdn/shop/articles/nico_robin_wano_kuni_one-piece_09576be8-66cf-43e9-a6d0-646ba903a442.jpg?v=1759943835',
    fruit: {
      name: 'Hana Hana no Mi',
      type: 'paramecia',
      description: 'Fruit permettant de faire pousser des copies de ses membres sur n\'importe quelle surface. Robin peut ainsi créer jusqu\'à mille bras en simultané et briser les corps des adversaires.',
      abilities: ['Floraison de membres', 'Gigante — corps géant de fleurs', 'Attaques simultanées multiples', 'Immobilisation'],
      color: '#EC4899',
    },
  },
  {
    id: 'bonney',
    name: 'Jewelry Bonney',
    title: 'Capitaine des Bonney Pirates',
    bounty: '1 000 000 000',
    epithet: 'Grande Mangeuse',
    image: 'https://image.jeuxvideo.com/medias-crop-1200-675/171960/1719603247-2716-card.jpg',
    fruit: {
      name: 'Toshi Toshi no Mi',
      type: 'paramecia',
      description: 'Fruit permettant de modifier l\'âge des cibles ou le sien propre. Bonney peut rajeunir ou vieillir instantanément quiconque elle touche, créant des scénarios de combat imprévisibles.',
      abilities: ['Modification de l\'âge', 'Rajeunissement', 'Vieillissement accéléré', 'Projection de désirs'],
      color: '#F472B6',
    },
  },
  {
    id: 'magellan',
    name: 'Magellan',
    title: 'Ancien Chef de Impel Down',
    bounty: null,
    epithet: 'Gardien de l\'Enfer',
    image: 'https://i.ytimg.com/vi/592XWC7Abkc/hq720.jpg',
    fruit: {
      name: 'Doku Doku no Mi',
      type: 'paramecia',
      description: 'Fruit du poison absolu. Magellan produit toutes sortes de poisons dans son corps — depuis les venins paralysants jusqu\'au poison hydra, pour lequel aucun antidote n\'existe.',
      abilities: ['Corps de poison', 'Hydra — neuf têtes venimeuses', 'Poison paralysant', 'Venin sans antidote'],
      color: '#7C3AED',
    },
  },
  {
    id: 'bartolomeo',
    name: 'Bartolomeo',
    title: 'Capitaine des Barto Club',
    bounty: '600 000 000',
    epithet: 'Le Cannibale',
    image: 'https://cdn.shopify.com/s/files/1/0747/3829/products/mZ1732_e0f39deb-d595-46b1-8641-4648aee2695e.jpg?v=1748539679',
    fruit: {
      name: 'Bari Bari no Mi',
      type: 'paramecia',
      description: 'Fruit permettant de créer des barrières indestructibles. Ces barrières résistent à tous les types d\'attaque physique et sont utilisées aussi bien défensivement qu\'offensivement.',
      abilities: ['Barrières indestructibles', 'Bouclier défensif', 'Lame de barrière', 'Mur offensif'],
      color: '#10B981',
    },
  },
  {
    id: 'shiliew',
    name: 'Shiliew de la Pluie',
    title: 'Commandant des Blackbeard Pirates',
    bounty: null,
    epithet: 'Bourreau d\'Impel Down',
    image: 'https://media.tenor.com/l7aIWJKH8nYAAAAe/one-piece-shiryu.png',
    fruit: {
      name: 'Suke Suke no Mi',
      type: 'paramecia',
      description: 'Fruit de l\'invisibilité, anciennement possédé par Absalom. Shiliew peut rendre son corps et tout ce qu\'il touche entièrement invisible. Combiné à son sabre, il devient un assassin imparable.',
      abilities: ['Invisibilité totale', 'Invisibilité des objets', 'Attaques imperceptibles', 'Lame fantôme'],
      color: '#6B7280',
    },
  },
]
